# Generated by Django 6.0.7 on 2026-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_contactinfo_map_latitude_contactinfo_map_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_iframe_url',
            field=models.TextField(blank=True, help_text='Скопируй сюда код из «Поделиться → HTML-код для сайта»', null=True, verbose_name='HTML iframe карты'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zoom',
            field=models.PositiveSmallIntegerField(default=17, verbose_name='Масштаб (зум)'),
        ),
    ]
