# Generated by Django 6.0.7 on 2026-07-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_contactinfo_map_iframe_url_alter_contactinfo_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_iframe_url',
            field=models.TextField(blank=True, help_text='<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A221a76d2fd650a12d87390ffd2acf934652d7d8d2c487967f8dd1001a3fe1dff&amp;source=constructor" width="100%" frameborder="0" style="border:none;" allowfullscreen=""></iframe>', null=True, verbose_name='HTML iframe карты'),
        ),
    ]
