# Generated by Django 6.0.7 on 2026-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(default='2024-01-01 12:00:00', verbose_name='Дата и время записи'),
            preserve_default=False,
        ),
    ]
