# Generated by Django 6.0.7 on 2026-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_remove_booking_time_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexample',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_examples/', verbose_name='Фото работы'),
        ),
    ]
